#!/usr/bin/bash
c='\e[0;34m'
o='\033[92m'
l='\e[1;32m'

echo -e $o" _________   _____   _     _   _____   ______"
echo -e $o"| __  __  | | __  | | |   | | | ___ | |  _  |"
echo -e $o"| | | | | | | | | | | |_  | | | | | | | | | |"
echo -e $o"|_| |_| |_| |_____| |___| |_| |_| |_| |  -  |"
echo -e $o"                          __________________|"
echo -e $o"                         |________________--|"

echo -e $c"site:"
read a
wget $a

echo -e $l "file saved(index html)"


